apiVersion: v1
kind: Service
metadata:
  name: chatcall-service
  labels:
    app: chatcall
spec:
  type: NodePort
  selector:
    app: chatcall
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
